// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/15/2025, 5:12:01 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Fikri Azman/Documents/GitHub/portfolio-nuxt3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Fikri Azman/Documents/GitHub/portfolio-nuxt3/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Fikri Azman/Documents/GitHub/portfolio-nuxt3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Fikri Azman/Documents/GitHub/portfolio-nuxt3/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Fikri Azman/Documents/GitHub/portfolio-nuxt3/plugins/**/*.{js,ts,mjs}","C:/Users/Fikri Azman/Documents/GitHub/portfolio-nuxt3/composables/**/*.{js,ts,mjs}","C:/Users/Fikri Azman/Documents/GitHub/portfolio-nuxt3/utils/**/*.{js,ts,mjs}","C:/Users/Fikri Azman/Documents/GitHub/portfolio-nuxt3/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Fikri Azman/Documents/GitHub/portfolio-nuxt3/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Fikri Azman/Documents/GitHub/portfolio-nuxt3/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Fikri Azman/Documents/GitHub/portfolio-nuxt3/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;