// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/11/2025, 10:56:55 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Fikri Azman/Desktop/Portfolio Website/nuxt3-portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Fikri Azman/Desktop/Portfolio Website/nuxt3-portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Fikri Azman/Desktop/Portfolio Website/nuxt3-portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Fikri Azman/Desktop/Portfolio Website/nuxt3-portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Fikri Azman/Desktop/Portfolio Website/nuxt3-portfolio/plugins/**/*.{js,ts,mjs}","C:/Users/Fikri Azman/Desktop/Portfolio Website/nuxt3-portfolio/composables/**/*.{js,ts,mjs}","C:/Users/Fikri Azman/Desktop/Portfolio Website/nuxt3-portfolio/utils/**/*.{js,ts,mjs}","C:/Users/Fikri Azman/Desktop/Portfolio Website/nuxt3-portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Fikri Azman/Desktop/Portfolio Website/nuxt3-portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Fikri Azman/Desktop/Portfolio Website/nuxt3-portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Fikri Azman/Desktop/Portfolio Website/nuxt3-portfolio/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;